CREATE TABLE IF NOT EXISTS `leadflow_jobs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `origin` varchar(32) NOT NULL,
  `launch27BookingId` int,
  `bookingSeriesId` int,
  `jobDate` varchar(10) NOT NULL,
  `serviceDateTime` varchar(50),
  `customerName` varchar(255) NOT NULL,
  `customerPhone` varchar(30),
  `customerEmail` varchar(320),
  `jobAddress` varchar(500),
  `serviceName` varchar(500),
  `bedrooms` int,
  `bathrooms` int,
  `extras` text,
  `frequency` varchar(100),
  `bookingStatus` varchar(50) NOT NULL,
  `teamName` varchar(255),
  `teamId` int,
  `customerNotes` text,
  `jobTotalCents` int NOT NULL DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `leadflow_jobs_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_leadflow_jobs_launch27_booking` UNIQUE(`launch27BookingId`),
  CONSTRAINT `uq_leadflow_jobs_series_date` UNIQUE(`bookingSeriesId`, `jobDate`),
  KEY `idx_leadflow_jobs_job_date` (`jobDate`),
  KEY `idx_leadflow_jobs_status_date` (`bookingStatus`, `jobDate`)
);
