CREATE TABLE IF NOT EXISTS `cleaner_portal_job_executions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `recordKind` varchar(20) NOT NULL,
  `sourceId` int NOT NULL,
  `cleanerProfileId` int NOT NULL,
  `teamId` int NOT NULL,
  `jobStatus` varchar(50) NOT NULL DEFAULT 'assigned',
  `etaTimestamp` bigint,
  `etaTimeStr` varchar(100),
  `delayMinutes` int,
  `arrivedAt` datetime(3),
  `startedAt` datetime(3),
  `completedAt` datetime(3),
  `signatureUrl` varchar(1000),
  `customerResponse` varchar(50),
  `customerNotes` text,
  `customerNotHome` tinyint NOT NULL DEFAULT 0,
  `jobRevenueCents` int NOT NULL DEFAULT 0,
  `payPercent` varchar(10),
  `basePayCents` int NOT NULL DEFAULT 0,
  `photoAdjustmentCents` int NOT NULL DEFAULT 0,
  `ratingAdjustmentCents` int NOT NULL DEFAULT 0,
  `manualAdjustmentCents` int NOT NULL DEFAULT 0,
  `finalPayCents` int NOT NULL DEFAULT 0,
  `checklistItems` text,
  `cleanerNotes` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `cleaner_portal_job_executions_id` PRIMARY KEY(`id`),
  CONSTRAINT `uq_cleaner_portal_execution_source` UNIQUE(`recordKind`,`sourceId`),
  KEY `idx_cleaner_portal_execution_team_status` (`teamId`,`jobStatus`),
  KEY `idx_cleaner_portal_execution_cleaner` (`cleanerProfileId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `cleaner_portal_job_photos` (
  `id` int AUTO_INCREMENT NOT NULL,
  `recordKind` varchar(20) NOT NULL,
  `sourceId` int NOT NULL,
  `cleanerPortalJobExecutionId` int,
  `cleanerProfileId` int NOT NULL,
  `photoUrl` varchar(1000) NOT NULL,
  `photoKey` varchar(1000) NOT NULL,
  `thumbnailUrl` varchar(1000),
  `thumbnailKey` varchar(1000),
  `filename` varchar(255),
  `photoType` varchar(20) NOT NULL DEFAULT 'general',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `cleaner_portal_job_photos_id` PRIMARY KEY(`id`),
  KEY `idx_cleaner_portal_photos_source` (`recordKind`,`sourceId`),
  KEY `idx_cleaner_portal_photos_cleaner` (`cleanerProfileId`)
);
