CREATE TABLE IF NOT EXISTS `madison_decisions` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `sourceMessageId` varchar(128) NOT NULL,
  `sessionId` bigint NOT NULL,
  `customerId` varchar(128),
  `summary` text NOT NULL,
  `disposition` enum('NO_ACTION','REPLY_ONLY','ACTION_REQUIRED','CLARIFICATION_REQUIRED','ANALYSIS_PENDING') NOT NULL,
  `replyRecommended` tinyint NOT NULL DEFAULT 0,
  `replyDraft` text,
  `uncertainties` json NOT NULL,
  `contextUsed` json NOT NULL,
  `modelProvider` varchar(64) NOT NULL,
  `modelName` varchar(128) NOT NULL,
  `modelVersion` varchar(128),
  `promptVersion` varchar(64) NOT NULL,
  `schemaVersion` varchar(64) NOT NULL,
  `validatorVersion` varchar(64) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_decisions_source_message` (`sourceMessageId`),
  KEY `idx_madison_decisions_session_created` (`sessionId`,`createdAt`),
  KEY `idx_madison_decisions_disposition_created` (`disposition`,`createdAt`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `madison_intents` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `decisionId` bigint NOT NULL,
  `intentKey` varchar(64) NOT NULL,
  `intentType` enum('INFORMATIONAL','NEW_BOOKING','MODIFY_BOOKING','CANCEL_BOOKING','SERVICE_REQUEST','SERVICE_COMPLAINT','PAYMENT_ISSUE','REFUND_CREDIT','TEAM_ETA','CUSTOMER_INFO_UPDATE','OTHER_OPERATIONAL','UNCLEAR') NOT NULL,
  `confidence` decimal(5,4),
  `evidence` json NOT NULL,
  `uncertainties` json NOT NULL,
  `target` json NOT NULL,
  `request` json NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_intents_decision_key` (`decisionId`,`intentKey`),
  KEY `idx_madison_intents_decision` (`decisionId`),
  KEY `idx_madison_intents_type` (`intentType`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `madison_action_proposals` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `intentId` bigint NOT NULL,
  `decisionId` bigint NOT NULL,
  `proposalKey` varchar(96) NOT NULL,
  `actionType` enum('RESCHEDULE_BOOKING','CANCEL_BOOKING','SERVICE_ISSUE_REVIEW','REFUND_CREDIT_REVIEW','OTHER_OPERATION') NOT NULL,
  `operation` enum('CHANGE_DATE','CHANGE_TIME','ADD_EXTRA','REMOVE_EXTRA','CHANGE_SERVICE','CHANGE_FREQUENCY','CHANGE_ADDRESS','CHANGE_ACCESS_INSTRUCTIONS','CHANGE_ARRIVAL_INSTRUCTIONS','OTHER_MODIFICATION'),
  `parameters` json NOT NULL,
  `targetType` varchar(32) NOT NULL,
  `targetId` varchar(128),
  `occurrenceKey` varchar(128),
  `riskLevel` tinyint NOT NULL,
  `readiness` enum('READY_FOR_HUMAN_REVIEW','MISSING_PARAMETERS','TARGET_UNRESOLVED','POLICY_REVIEW_REQUIRED','CONFLICTING_STATE') NOT NULL,
  `missingParameters` json NOT NULL,
  `verificationSteps` json NOT NULL,
  `expectedCurrentState` json NOT NULL,
  `bookingVersion` varchar(128),
  `actionFingerprint` varchar(128) NOT NULL,
  `status` enum('PROPOSED','NEEDS_REVIEW','APPROVING','APPROVED','DISMISSED','SUPERSEDED','PENDING_EXECUTION','EXECUTING','COMPLETED','FAILED') NOT NULL DEFAULT 'PROPOSED',
  `supersededByProposalId` bigint,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_action_proposals_key` (`proposalKey`),
  UNIQUE KEY `uq_madison_action_proposals_fingerprint` (`actionFingerprint`),
  KEY `idx_madison_action_proposals_intent` (`intentId`),
  KEY `idx_madison_action_proposals_decision` (`decisionId`),
  KEY `idx_madison_action_proposals_status_created` (`status`,`createdAt`),
  KEY `idx_madison_action_proposals_target` (`targetId`),
  KEY `idx_madison_action_proposals_superseded` (`supersededByProposalId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `madison_action_approvals` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `proposalId` bigint NOT NULL,
  `decision` enum('APPROVE','DISMISS','WRONG_ACTION') NOT NULL,
  `correctedActionType` enum('RESCHEDULE_BOOKING','CANCEL_BOOKING','SERVICE_ISSUE_REVIEW','REFUND_CREDIT_REVIEW','OTHER_OPERATION'),
  `correctionReason` varchar(64),
  `correctedBy` varchar(128) NOT NULL,
  `createdIssueId` bigint,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_madison_action_approvals_proposal_created` (`proposalId`,`createdAt`),
  KEY `idx_madison_action_approvals_issue` (`createdIssueId`),
  KEY `idx_madison_action_approvals_decision_created` (`decision`,`createdAt`)
);
