import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, ClipboardList, Home, Sparkles, Wrench } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { CUSTOMER_PORTAL_SERVICES, type CustomerPortalService } from "@shared/customerPortalServices";
import "./customer-portal.css";

function ServiceRequestForm({ service, onClose }: { service: CustomerPortalService; onClose: () => void }) {
  const utils = trpc.useUtils();
  const createRequest = trpc.customerPortal.createRequest.useMutation({ onSuccess: () => { void utils.customerPortal.me.invalidate(); onClose(); } });
  const [selections, setSelections] = useState<Record<string, string>>({});
  const [address, setAddress] = useState(""); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [notes, setNotes] = useState("");
  const canSubmit = service.fields.every(field => selections[field.label]?.trim()) && address.trim().length >= 5 && Boolean(date) && Boolean(time);
  return <div className="mib-portal-modal" role="dialog" aria-modal="true" aria-labelledby="mib-service-title"><div className="mib-portal-modal-card"><button className="mib-portal-close" type="button" onClick={onClose} aria-label="Close request form">×</button><small>MAIDS IN BLACK · HOME SERVICES</small><h2 id="mib-service-title">Book {service.name}</h2><p>{service.detail}. Starting at ${service.startingPrice}; the final scope is confirmed by our team.</p><div className="mib-portal-form-fields">{service.fields.map(field => <label key={field.label}><span>{field.label}</span>{field.options ? <select value={selections[field.label] ?? ""} onChange={event => setSelections(current => ({ ...current, [field.label]: event.target.value }))}><option value="">Choose one</option>{field.options.map(option => <option key={option}>{option}</option>)}</select> : <textarea placeholder={field.placeholder} value={selections[field.label] ?? ""} onChange={event => setSelections(current => ({ ...current, [field.label]: event.target.value }))} />}</label>)}<label><span>Service address</span><input value={address} onChange={event => setAddress(event.target.value)} placeholder="Street address" /></label><div className="mib-portal-form-row"><label><span>Preferred date</span><input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label><span>Preferred time</span><input value={time} onChange={event => setTime(event.target.value)} placeholder="Morning, afternoon, etc." /></label></div><label><span>Anything else?</span><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Optional details" /></label></div>{createRequest.error && <p className="mib-portal-error">{createRequest.error.message}</p>}<button type="button" className="mib-portal-primary" disabled={!canSubmit || createRequest.isPending} onClick={() => createRequest.mutate({ serviceId: service.id, selections, address, requestedLocalDate: date, requestedLocalTime: time, notes: notes || undefined })}>{createRequest.isPending ? "Sending request…" : "Send service request"}<ArrowRight /></button></div></div>;
}

export default function CustomerPortal() {
  const utils = trpc.useUtils(); const [selectedService, setSelectedService] = useState<CustomerPortalService | null>(null); const [accessHandled, setAccessHandled] = useState(false);
  const redeem = trpc.customerPortal.redeemHandoff.useMutation({ onSuccess: () => { window.history.replaceState({}, "", "/my-home"); void utils.customerPortal.me.invalidate(); setAccessHandled(true); }, onError: () => setAccessHandled(true) });
  const portal = trpc.customerPortal.me.useQuery(undefined, { enabled: accessHandled || !new URLSearchParams(window.location.search).get("access") });
  useEffect(() => { const code = new URLSearchParams(window.location.search).get("access"); if (code) redeem.mutate({ code }); else setAccessHandled(true); }, []); // A provided handoff is consumed once.
  const activeCount = useMemo(() => (portal.data?.cleanings.length ?? 0) + (portal.data?.requests.length ?? 0), [portal.data]);
  if (!accessHandled || portal.isLoading) return <main className="mib-portal-gate">Loading your home portal…</main>;
  if (!portal.data?.account) return <main className="mib-portal-gate"><div className="mib-portal-mark">M</div><small>MAIDS IN BLACK · MY HOME</small><h1>Everything for your home, in one place.</h1><p>Your portal opens from your booking confirmation on this device.</p><a className="mib-portal-primary" href="/book-now">Book home cleaning <ArrowRight /></a></main>;
  return <main className="mib-portal-shell"><header className="mib-portal-topbar"><a href="/my-home"><span>M</span> Maids in Black</a><b>{portal.data.account.name.split(" ")[0]}</b></header><section className="mib-portal-hero"><div><small>MY HOME · MAIDS IN BLACK</small><h1>Welcome back, {portal.data.account.name.split(" ")[0]}.</h1><p>Your cleaning and home-service requests are together here.</p></div><a className="mib-portal-primary" href="/book-now">Book home cleaning <ArrowRight /></a></section><section className="mib-portal-stats"><article><ClipboardList /><div><span>Home requests</span><strong>{activeCount}</strong></div></article><article><CalendarDays /><div><span>Cleaning bookings</span><strong>{portal.data.cleanings.length}</strong></div></article><article><CheckCircle2 /><div><span>Portal status</span><strong>Active</strong></div></article></section><section className="mib-portal-section"><div className="mib-portal-heading"><div><small>MORE WAYS WE CAN HELP</small><h2>Book another home service.</h2></div><span>12 services</span></div><div className="mib-portal-services"><a className="mib-portal-service cleaning" href="/book-now"><Home /><div><strong>Home cleaning</strong><p>One-time or recurring</p><em>Book cleaning <ArrowRight /></em></div></a>{CUSTOMER_PORTAL_SERVICES.map(service => <button className="mib-portal-service" type="button" key={service.id} onClick={() => setSelectedService(service)}><Wrench /><div><strong>{service.name}</strong><p>{service.detail}</p><em>Start request <ArrowRight /></em></div></button>)}</div></section><section className="mib-portal-section"><div className="mib-portal-heading"><div><small>YOUR HOME</small><h2>Bookings & requests</h2></div></div><div className="mib-portal-records">{activeCount === 0 ? <div className="mib-portal-empty"><Sparkles /><h3>Your home history starts here.</h3><p>Your cleaning and service requests will appear here.</p></div> : <>{portal.data.cleanings.map((cleaning: any) => <article className="mib-portal-record" key={`cleaning-${cleaning.id}`}><div><small>HOME CLEANING</small><h3>{cleaning.serviceName}</h3><p>{cleaning.requestedLocalDate} · {cleaning.requestedLocalTime || "Time to be confirmed"}</p></div><b>{cleaning.status.replace(/_/g, " ")}</b></article>)}{portal.data.requests.map((request: any) => <article className="mib-portal-record" key={`request-${request.id}`}><div><small>HOME SERVICE REQUEST</small><h3>{request.serviceName}</h3><p>{request.requestedLocalDate} · {request.requestedLocalTime}</p></div><b>{request.status}</b></article>)}</>}</div></section>{selectedService && <ServiceRequestForm service={selectedService} onClose={() => setSelectedService(null)} />}</main>;
}
