export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openPhoneApiKey: process.env.OPENPHONE_API_KEY ?? "",
  openPhoneNumberId: process.env.OPENPHONE_PHONE_NUMBER_ID ?? "",
  openPhoneFromNumber: process.env.OPENPHONE_FROM_NUMBER ?? "",
  launch27BearerToken: process.env.LAUNCH27_BEARER_TOKEN ?? "",
  launch27Subdomain: process.env.LAUNCH27_TENANT ?? process.env.LAUNCH27_SUBDOMAIN ?? "maidsinblack",
  vapiPrivateKey: process.env.VAPI_PRIVATE_KEY ?? "",
  vapiPublicKey: process.env.VAPI_PUBLIC_KEY ?? "",
  mailgunWebhookSigningKey: process.env.MAILGUN_WEBHOOK_SIGNING_KEY ?? "",
};
