export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ?? "",
  openPhoneApiKey: process.env.OPENPHONE_API_KEY ?? "",
  openPhoneNumberId: process.env.OPENPHONE_PHONE_NUMBER_ID ?? "",
  openPhoneCsNumberId: process.env.OPENPHONE_CS_PHONE_NUMBER_ID ?? "",
  openPhoneBarkNumberId: process.env.OPENPHONE_BARK_PHONE_NUMBER_ID ?? "",
  openPhoneFromNumber: process.env.OPENPHONE_FROM_NUMBER ?? "",
  launch27BearerToken: process.env.LAUNCH27_BEARER_TOKEN ?? "",
  launch27Subdomain: process.env.LAUNCH27_TENANT ?? process.env.LAUNCH27_SUBDOMAIN ?? "maidsinblack",
  vapiPrivateKey: process.env.VAPI_PRIVATE_KEY ?? "",
  vapiPublicKey: process.env.VAPI_PUBLIC_KEY ?? "",
  vapiWebhookUrl: process.env.VAPI_WEBHOOK_URL ?? "https://quote.maidinblack.com/api/webhooks/vapi",
  mailgunWebhookSigningKey: process.env.MAILGUN_WEBHOOK_SIGNING_KEY ?? "",
  zapierWebhookSecret: process.env.ZAPIER_WEBHOOK_SECRET ?? "",
  quoteAppSecret: process.env.QUOTE_APP_SECRET ?? "",
  quoteAppUrl: process.env.QUOTE_APP_URL ?? "https://maidsquotes-b55s3sg4.manus.space",
  businessTimezone: process.env.BUSINESS_TIMEZONE ?? "America/Los_Angeles",
  isPreviewMode: process.env.PREVIEW_MODE === "true",
  gmailClientId: process.env.GMAIL_CLIENT_ID ?? "",
  gmailClientSecret: process.env.GMAIL_CLIENT_SECRET ?? "",
  gmailRedirectUri: process.env.GMAIL_REDIRECT_URI ?? "https://quote.maidinblack.com/api/gmail/oauth/callback",
  gmailRefreshToken: process.env.GMAIL_REFRESH_TOKEN ?? "",
  gmailPubsubTopic: process.env.GMAIL_PUBSUB_TOPIC ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripePublishableKey: process.env.STRIPE_PUBLISHABLE_KEY ?? "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? "",
};
