import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const read = (relativePath: string) => fs.readFileSync(path.join(root, relativePath), "utf8");

describe("Review Workspace live destinations", () => {
  it("keeps review links for static pages and uses live routes for completed exact migrations", () => {
    const nav = read("client/src/components/ReviewWorkspaceNav.tsx");
    const navStyles = read("client/src/components/review-workspace-nav.css");
    const app = read("client/src/App.tsx");

    expect(nav).toContain('liveHref: "/admin/command-chat"');
    expect(nav).toContain('liveHref: "/admin/bookings"');
    expect(nav).toContain('liveHref: "/admin/customer-profile"');
    expect(nav).toContain('liveHref: "/admin/confirmation-calls"');
    expect(nav).toContain('liveHref: "/admin/invoices"');
    expect(nav).toContain('liveHref: "/admin/payments"');
    expect(nav).toContain('liveHref: "/admin/team"');
    expect(nav).toContain('liveHref: "/admin/payroll-summary"');
    expect(nav).toContain('liveHref: "/admin/schedule"');
    expect(nav).toContain('liveHref: "/admin/day-board"');
    expect(nav).toContain('liveHref: "/admin/sms"');
    expect(nav).toContain('liveHref: "/admin/emails"');
    expect(nav).toContain('liveHref: "/admin/ai-calls"');
    expect(nav).toContain('const settingsHref = useLiveDestinations ? "/admin/settings" : "/review/settings";');
    expect(nav).toContain('const href = useLiveDestinations ? item.liveHref ?? item.href : item.href;');
    expect(nav).toContain('href={href}');
    expect(nav).toContain('href: "/review/payments"');
    expect(nav).toContain('href: "/review/schedule-crm"');
    expect(nav).toContain('aria-label="Baseboard navigation"');
    expect(nav).toContain('<span className="review-workspace-toggle-copy"><strong>Baseboard</strong></span>');
    expect(nav).toContain('<div className="review-workspace-footer"><span>Static pages</span><small>18 workspaces</small></div>');
    expect(nav).not.toContain('<strong>Workspaces</strong>');
    expect(nav).not.toContain('<small>Review only</small>');
    expect(navStyles).toContain('grid-template:repeat(2,10px)/repeat(2,10px)');
    expect(navStyles).toContain('.review-workspace-mark i:nth-child(1){background:#e78364}');
    expect(navStyles).toContain('.review-workspace-mark i:nth-child(2){background:#8bb4d9}');
    expect(navStyles).toContain('.review-workspace-mark i:nth-child(3){background:#b083d3}');
    expect(navStyles).toContain('.review-workspace-mark i:nth-child(4){background:#80cba9}');
    expect(navStyles).toContain('a.is-active{border-color:#74513e;background:#3b2921;color:#e7b38d');
    expect(navStyles).toContain('.review-workspace-nav:not(.is-expanded) .review-workspace-group{padding-left:8px;padding-right:8px}');
    expect(navStyles).toContain('.review-workspace-nav:not(.is-expanded) .review-workspace-group a span{display:none}');
    expect(nav).toContain('const [tooltip, setTooltip] = useState<{ label: string; top: number } | null>(null);');
    expect(nav).toContain('const showBaseboardTooltip = (event: MouseEvent<HTMLElement> | FocusEvent<HTMLElement>, label: string) => {');
    expect(nav).toContain('onMouseEnter={(event) => showBaseboardTooltip(event, item.label)}');
    expect(nav).toContain('onFocus={(event) => showBaseboardTooltip(event, item.label)}');
    expect(nav).toContain('className="review-workspace-tooltip" role="tooltip"');
    expect(navStyles).toContain('.review-workspace-tooltip{position:absolute');
    expect(navStyles).toContain('top:var(--baseboard-tooltip-top)');
    expect(nav).not.toContain("setTimeout(");
    const tooltipCss = navStyles.slice(navStyles.indexOf(".review-workspace-tooltip"));
    expect(tooltipCss).not.toContain("transition:");

    expect(app).toContain('<Route path={"/admin/command-chat"} component={AdminCommandChatExactLiveRoute} />');
    expect(app).toContain('function AdminCommandChatExactLiveRoute()');
    expect(app).toContain('<ReviewWorkspaceFrame navActivePath="/review/command-chat-crm"><CommandChatExactLive /></ReviewWorkspaceFrame>');
    const defaultOpenRoutes = nav.slice(nav.indexOf("const defaultOpenRoutes"), nav.indexOf("const routeKey"));
    expect(defaultOpenRoutes).not.toContain("/review/command-chat-crm");
    expect(app).toContain('<Route path={"/admin/bookings"} component={AdminBookingsCRMExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/customer-profile"} component={AdminCustomerProfileExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/confirmation-calls"} component={AdminConfirmationCallsExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/invoices"} component={AdminInvoicesExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/payments"} component={AdminPaymentsExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/team"} component={AdminTeamExactLiveRoute} />');
    expect(app).toContain('<Route path={"/admin/payroll-summary"} component={PayrollSummary} />');
    expect(app).toContain('<Route path={"/admin/schedule"} component={AdminScheduleCRMExactRoute} />');
    expect(app).toContain('<Route path={"/admin/day-board"} component={AdminDayBoardExactLiveRoute} />');
    expect(app).toContain('<Route path={"/admin/sms"} component={AdminSmsExactLiveRoute} />');
    expect(app).toContain('<Route path={"/admin/emails"} component={AdminEmailsExactLiveRoute} />');
    expect(app).toContain('<Route path={"/admin/ai-calls"} component={AdminAiCallsExactReviewRoute} />');
    expect(app).toContain('<Route path={"/admin/settings"} component={AdminSettingsReviewRoute} />');
  });
});
