CREATE TABLE IF NOT EXISTS `bookings` (
  `id` int AUTO_INCREMENT NOT NULL,
  `publicBookingNumber` varchar(40) NOT NULL,
  `idempotencyKey` varchar(36) NOT NULL,
  `commandHash` varchar(64) NOT NULL,
  `source` varchar(20) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'needs_attention',
  `availabilityStatus` varchar(32) NOT NULL DEFAULT 'requested',
  `assignmentStatus` varchar(32) NOT NULL DEFAULT 'unassigned',
  `paymentStatus` varchar(32) NOT NULL DEFAULT 'not_started',
  `customerName` varchar(255) NOT NULL,
  `customerPhone` varchar(20) NOT NULL,
  `customerEmail` varchar(320) NOT NULL,
  `serviceId` varchar(32) NOT NULL,
  `serviceName` varchar(120) NOT NULL,
  `bedrooms` int NOT NULL,
  `bathrooms` int NOT NULL,
  `extras` json NOT NULL,
  `specialRequestNotes` json NOT NULL,
  `address` varchar(500) NOT NULL,
  `requestedLocalDate` varchar(10) NOT NULL,
  `requestedLocalTime` varchar(5) NOT NULL,
  `requestedTimeZone` varchar(64) NOT NULL,
  `requestedStartAt` bigint NOT NULL,
  `recurrence` varchar(32) NOT NULL DEFAULT 'one-time',
  `recurringIntentStatus` varchar(32),
  `pricingVersion` varchar(64) NOT NULL,
  `firstCleaningTotalCents` int NOT NULL,
  `futureVisitTotalCents` int,
  `priceSnapshot` json NOT NULL,
  `expiresAt` bigint,
  `createdAt` datetime(3) NOT NULL,
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_bookings_public_number` (`publicBookingNumber`),
  UNIQUE KEY `uq_bookings_idempotency_key` (`idempotencyKey`),
  KEY `idx_bookings_requested_date` (`requestedLocalDate`),
  KEY `idx_bookings_status_date` (`status`, `requestedLocalDate`),
  KEY `idx_bookings_customer_phone` (`customerPhone`)
);
