CREATE TABLE IF NOT EXISTS `booking_funnel_records` (
  `id` int AUTO_INCREMENT NOT NULL,
  `publicFunnelNumber` varchar(40) NOT NULL,
  `idempotencyKey` varchar(36) NOT NULL,
  `commandHash` varchar(64) NOT NULL,
  `source` varchar(24) NOT NULL,
  `stage` varchar(32) NOT NULL DEFAULT 'lead',
  `customerName` varchar(255) NOT NULL,
  `customerPhone` varchar(20) NOT NULL,
  `customerEmail` varchar(320),
  `serviceId` varchar(32),
  `serviceName` varchar(120),
  `bedrooms` int,
  `bathrooms` int,
  `extras` json,
  `specialRequestNotes` json,
  `address` varchar(500),
  `requestedLocalDate` varchar(10),
  `requestedLocalTime` varchar(5),
  `requestedTimeZone` varchar(64),
  `recurrence` varchar(32),
  `pricingVersion` varchar(64),
  `firstCleaningTotalCents` int,
  `futureVisitTotalCents` int,
  `priceSnapshot` json,
  `stripeCustomerId` varchar(255),
  `stripePaymentMethodId` varchar(255),
  `paymentBrand` varchar(40),
  `paymentLast4` varchar(4),
  `version` int NOT NULL DEFAULT 1,
  `createdAt` datetime(3) NOT NULL,
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_funnel_public_number` (`publicFunnelNumber`),
  UNIQUE KEY `uq_booking_funnel_idempotency_key` (`idempotencyKey`),
  KEY `idx_booking_funnel_phone` (`customerPhone`),
  KEY `idx_booking_funnel_stage_updated` (`stage`, `updatedAt`)
);
