CREATE TABLE IF NOT EXISTS `booking_payment_profiles` (
  `id` int AUTO_INCREMENT NOT NULL,
  `bookingId` int NOT NULL,
  `funnelRecordId` int NOT NULL,
  `paymentStatus` varchar(32) NOT NULL DEFAULT 'not_started',
  `version` int NOT NULL DEFAULT 1,
  `stripeCustomerId` varchar(255),
  `stripePaymentMethodId` varchar(255),
  `stripeSetupIntentId` varchar(255),
  `stripePaymentIntentId` varchar(255),
  `cardBrand` varchar(40),
  `cardLast4` varchar(4),
  `cardExpMonth` int,
  `cardExpYear` int,
  `consentVersion` varchar(64),
  `consentText` text,
  `consentAcceptedAt` bigint,
  `authorizationExpiresAt` bigint,
  `authorizedAt` bigint,
  `capturedAt` bigint,
  `failureCode` varchar(128),
  `failureMessage` text,
  `createdAt` datetime(3) NOT NULL,
  `updatedAt` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_payment_profile_booking` (`bookingId`),
  UNIQUE KEY `uq_booking_payment_profile_funnel` (`funnelRecordId`),
  UNIQUE KEY `uq_booking_payment_profile_setup_intent` (`stripeSetupIntentId`),
  KEY `idx_booking_payment_profile_status` (`paymentStatus`)
);
