CREATE TABLE IF NOT EXISTS `madison_decisions` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `sourceMessageId` varchar(128) NOT NULL,
  `sessionId` bigint NOT NULL,
  `customerId` varchar(128),
  `summary` text NOT NULL,
  `disposition` enum('NO_ACTION','REPLY_ONLY','ACTION_REQUIRED','CLARIFICATION_REQUIRED','ANALYSIS_PENDING') NOT NULL,
  `replyRecommended` tinyint NOT NULL DEFAULT 0,
  `replyDraft` text,
  `uncertainties` json NOT NULL,
  `contextUsed` json NOT NULL,
  `modelProvider` varchar(64) NOT NULL,
  `modelName` varchar(128) NOT NULL,
  `modelVersion` varchar(128),
  `promptVersion` varchar(64) NOT NULL,
  `schemaVersion` varchar(64) NOT NULL,
  `validatorVersion` varchar(64) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_decisions_source_message` (`sourceMessageId`),
  KEY `idx_madison_decisions_session_created` (`sessionId`,`createdAt`),
  KEY `idx_madison_decisions_disposition_created` (`disposition`,`createdAt`)
);
