CREATE TABLE IF NOT EXISTS `madison_action_proposals` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `intentId` bigint NOT NULL,
  `decisionId` bigint NOT NULL,
  `proposalKey` varchar(96) NOT NULL,
  `actionType` enum('RESCHEDULE_BOOKING','CANCEL_BOOKING','SERVICE_ISSUE_REVIEW','REFUND_CREDIT_REVIEW','OTHER_OPERATION') NOT NULL,
  `operation` enum('CHANGE_DATE','CHANGE_TIME','ADD_EXTRA','REMOVE_EXTRA','CHANGE_SERVICE','CHANGE_FREQUENCY','CHANGE_ADDRESS','CHANGE_ACCESS_INSTRUCTIONS','CHANGE_ARRIVAL_INSTRUCTIONS','OTHER_MODIFICATION'),
  `parameters` json NOT NULL,
  `targetType` varchar(32) NOT NULL,
  `targetId` varchar(128),
  `occurrenceKey` varchar(128),
  `riskLevel` tinyint NOT NULL,
  `readiness` enum('READY_FOR_HUMAN_REVIEW','MISSING_PARAMETERS','TARGET_UNRESOLVED','POLICY_REVIEW_REQUIRED','CONFLICTING_STATE') NOT NULL,
  `missingParameters` json NOT NULL,
  `verificationSteps` json NOT NULL,
  `expectedCurrentState` json NOT NULL,
  `bookingVersion` varchar(128),
  `actionFingerprint` varchar(128) NOT NULL,
  `status` enum('PROPOSED','NEEDS_REVIEW','APPROVING','APPROVED','DISMISSED','SUPERSEDED','PENDING_EXECUTION','EXECUTING','COMPLETED','FAILED') NOT NULL DEFAULT 'PROPOSED',
  `supersededByProposalId` bigint,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_action_proposals_key` (`proposalKey`),
  UNIQUE KEY `uq_madison_action_proposals_fingerprint` (`actionFingerprint`),
  KEY `idx_madison_action_proposals_intent` (`intentId`),
  KEY `idx_madison_action_proposals_decision` (`decisionId`),
  KEY `idx_madison_action_proposals_status_created` (`status`,`createdAt`),
  KEY `idx_madison_action_proposals_target` (`targetId`),
  KEY `idx_madison_action_proposals_superseded` (`supersededByProposalId`)
);
