CREATE TABLE IF NOT EXISTS `madison_message_understanding` (
  `id` bigint AUTO_INCREMENT NOT NULL,
  `sourceMessageId` varchar(128) NOT NULL,
  `draftId` bigint,
  `sessionId` bigint NOT NULL,
  `inboundText` text NOT NULL,
  `primaryCategory` varchar(64) NOT NULL,
  `categories` json NOT NULL,
  `mission` varchar(64) NOT NULL,
  `missionState` varchar(64) NOT NULL,
  `nextBestAction` varchar(64) NOT NULL,
  `confidence` decimal(5,4) NOT NULL,
  `knownFacts` json NOT NULL,
  `missingFacts` json NOT NULL,
  `resolvedCustomerId` varchar(128),
  `resolvedBookingId` bigint,
  `model` varchar(64) NOT NULL,
  `classifierVersion` varchar(64) NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_madison_message_understanding_source_version` (`sourceMessageId`, `classifierVersion`),
  KEY `idx_madison_message_understanding_session_created` (`sessionId`, `createdAt`),
  KEY `idx_madison_message_understanding_category_created` (`primaryCategory`, `createdAt`)
);
