export type CustomerPortalServiceField = { label: string; options?: readonly string[]; placeholder?: string };
export type CustomerPortalService = { id: string; name: string; startingPrice: number; detail: string; fields: readonly CustomerPortalServiceField[] };

export const CUSTOMER_PORTAL_SERVICES: readonly CustomerPortalService[] = [
  { id: "tv-mounting", name: "TV mounting", startingPrice: 149, detail: "One TV on a standard drywall wall", fields: [{ label: "TV count", options: ["One TV", "Two TVs", "Three or more"] }, { label: "TV size", options: ["Up to 43 inches", "44–65 inches", "Over 65 inches"] }, { label: "Wall & mount", options: ["Drywall and I have a mount", "Drywall and I need a mount", "Brick, stone, tile, or not sure"] }] },
  { id: "furniture-assembly", name: "Furniture assembly", startingPrice: 119, detail: "Small or standard item · two-hour minimum", fields: [{ label: "Small item count", options: ["0", "1", "2–3", "4+"] }, { label: "Medium item count", options: ["0", "1", "2–3", "4+"] }, { label: "Large item count", options: ["0", "1", "2+"] }, { label: "Planned service time", options: ["2 hours", "2.5 hours", "3 hours", "3.5+ hours"] }, { label: "Additional purchase or haul", options: ["No", "Yes"] }] },
  { id: "picture-hanging", name: "Picture hanging", startingPrice: 99, detail: "Up to two small standard-height items", fields: [{ label: "Small item count", options: ["0", "1–2", "3–5", "6+"] }, { label: "Large or heavy item count", options: ["0", "1", "2+"] }, { label: "Shelves to install", options: ["No", "1 shelf", "2+ shelves"] }, { label: "Ladder height", options: ["No ladder", "6 ft ladder", "10 ft ladder"] }, { label: "Planned service time", options: ["2 hours", "2.5 hours", "3 hours", "3.5+ hours"] }] },
  { id: "minor-home-repairs", name: "Minor home repairs", startingPrice: 129, detail: "One small repair · two-hour service minimum", fields: [{ label: "Repair type", options: ["Door, drawer, or hardware", "Patch, caulk, or touch-up", "Small household fix"] }, { label: "Task count", options: ["One repair", "Two or three repairs", "Several unrelated repairs"] }, { label: "Parts or hardware", options: ["I have them", "I need guidance", "Not sure"] }] },
  { id: "handyman", name: "Handyman visit", startingPrice: 129, detail: "Small repair · two-hour service minimum", fields: [{ label: "What needs help?", placeholder: "Describe the repair, install, or household task" }, { label: "How many tasks?", options: ["One task", "Two or three tasks", "Several unrelated tasks"] }, { label: "Parts or hardware", options: ["I have them", "I need guidance", "Not sure"] }, { label: "Planned service time", options: ["2 hours", "2.5 hours", "3 hours", "3.5+ hours"] }] },
  { id: "plumbing", name: "Plumbing help", startingPrice: 159, detail: "Minor diagnostic or repair visit", fields: [{ label: "Issue", options: ["Faucet or fixture", "Drain issue", "Toilet issue"] }, { label: "Access", options: ["Shutoff and plumbing are accessible", "Access is limited", "Not sure"] }, { label: "Urgency", options: ["Today if possible", "This week", "Not urgent"] }] },
  { id: "electrical-lighting", name: "Electrical & lighting", startingPrice: 149, detail: "One existing-access fixture or switch task", fields: [{ label: "Light fixtures", options: ["0", "1", "2", "3+"] }, { label: "Dimmers or switches", options: ["0", "1", "2", "3+"] }, { label: "Ceiling fans", options: ["0", "1", "2+"] }, { label: "Ladder height", options: ["No ladder", "6 ft ladder", "10 ft ladder"] }, { label: "Wiring access", options: ["Existing wiring is accessible", "Not sure", "New wiring or panel work"] }, { label: "Planned service time", options: ["2 hours", "2.5 hours", "3 hours", "3.5+ hours"] }] },
  { id: "interior-painting", name: "Interior painting", startingPrice: 199, detail: "Paint-ready touch-up or one standard accent wall", fields: [{ label: "Project type", options: ["Touch-ups", "One accent wall", "Room or multiple rooms"] }, { label: "Paint & prep", options: ["Paint is ready and wall is sound", "I need paint guidance", "Patching, prep, or wallpaper removal"] }, { label: "Access", options: ["Standard wall height", "Ceiling or trim included", "High access or furniture moving"] }] },
  { id: "moving-help", name: "Moving help", startingPrice: 238, detail: "One helper for two hours · no truck", fields: [{ label: "Help needed", options: ["Load my truck", "Unload my truck", "Move items inside my home"] }, { label: "Helpers", options: ["1 helper", "2 helpers", "3 helpers"] }, { label: "Duration", options: ["2 hours", "2.5 hours", "3 hours", "3.5+ hours"] }, { label: "Certificate of insurance", options: ["No", "Yes"] }, { label: "Boxes or materials", options: ["No", "Yes"] }, { label: "Building access", options: ["Ground floor / easy access", "Stairs or elevator", "Long carry or special item"] }] },
  { id: "lawn-yard-care", name: "Lawn & yard care", startingPrice: 49, detail: "Small maintained lawn · mow, edge, and blow", fields: [{ label: "Yard size", options: ["Small", "Medium", "Large"] }, { label: "Service", options: ["Mow, edge, and blow", "Trimming or weeding", "Seasonal cleanup"] }, { label: "Condition", options: ["Regularly maintained", "Overgrown", "Not sure"] }] },
  { id: "junk-removal", name: "Junk removal", startingPrice: 129, detail: "Small curbside or one-eighth truckload pickup", fields: [{ label: "Load size", options: ["A few items / one-eighth truck", "Quarter to half truck", "More than half a truck"] }, { label: "Pickup location", options: ["Curbside", "Garage / ground floor", "Stairs or elevator"] }, { label: "Items", options: ["Household items", "Furniture or mattress", "Appliance, electronics, or other"] }] },
  { id: "pressure-washing", name: "Pressure washing", startingPrice: 99, detail: "Small ground-level patio or walkway", fields: [{ label: "Area", options: ["Patio or walkway", "Driveway", "Siding, deck, or porch"] }, { label: "Size", options: ["Small", "Medium", "Large or multiple areas"] }, { label: "Access", options: ["Ground level with outdoor water", "No outdoor water", "Two stories, roof, or delicate surface"] }] },
];

export function getCustomerPortalService(id: string): CustomerPortalService | undefined { return CUSTOMER_PORTAL_SERVICES.find(service => service.id === id); }
export function validateCustomerPortalSelections(service: CustomerPortalService, selections: Record<string, string>): string | null {
  for (const field of service.fields) {
    const value = selections[field.label]?.trim();
    if (!value) return `Choose an option for ${field.label}.`;
    if (field.options && !field.options.includes(value)) return `Choose a valid option for ${field.label}.`;
  }
  return null;
}
